stages:
  - build

rust-latest:
  stage: build
  image: rust:latest
  script:
    - cargo install --debug cargo-make
    - cargo make ci-flow
    - cargo build --verbose
    - cargo test --verbose

rust-nightly:
  stage: build
  image: rustlang/rust:nightly
  script:
    - cargo install --debug cargo-make
    - cargo make ci-flow
    - cargo build --verbose
    - cargo test --verbose
  allow_failure: true

variables:
  CARGO_MAKE_RUN_CODECOV: "true"
