stages:
  - build

rust-latest:
  stage: build
  image: rust:latest
  before_script:
    - cargo install --debug cargo-make
    - cargo make coverage
  script:
    - cargo build --verbose
    - cargo test --verbose
    - cargo make ci-flow

rust-nightly:
  stage: build
  image: rustlang/rust:nightly
  before_script:
    - cargo install --debug cargo-make
    - cargo make coverage
  script:
    - cargo build --verbose
    - cargo test --verbose
    - cargo make ci-flow
  allow_failure: true

variables:
  CARGO_MAKE_RUN_CODECOV: "true"
