stages:
  - test
  - coverage

rust-latest:
  stage: test
  image: rust:latest
  script:
    - cargo build --verbose
    - cargo test --verbose

rust-nightly:
  stage: test
  image: rustlang/rust:nightly
  script:
    - cargo build --verbose
    - cargo test --verbose
  allow_failure: true

coverage:
  stage: coverage
  image: elrnv/rust-kcov:rust-1.42.0
  before_script:
    - cargo install --debug cargo-make
  script:
    - cargo make ci-flow

variables:
  CARGO_MAKE_RUN_CODECOV: "true"
